#pragma once
#include <ntifs.h>

#define READ CTL_CODE(FILE_DEVICE_UNKNOWN,0x333,METHOD_BUFFERED,FILE_SPECIAL_ACCESS)
#define DLL_ADDR_REQUEST CTL_CODE(FILE_DEVICE_UNKNOWN,0x334,METHOD_BUFFERED,FILE_SPECIAL_ACCESS)

#define Print(thing,...) DbgPrintEx(0,0,thing,__VA_ARGS__)

VOID Unload(IN PDRIVER_OBJECT driverObject);
NTSTATUS DriverEntry(IN PDRIVER_OBJECT driverObject, IN PCUNICODE_STRING registryPath);

NTSTATUS Control(PDEVICE_OBJECT DeviceObj, PIRP Irp);
NTSTATUS Create(PDEVICE_OBJECT DeviceObj, PIRP Irp);
NTSTATUS Close(PDEVICE_OBJECT DeviceObject, PIRP irp);



UNICODE_STRING DeviceName = RTL_CONSTANT_STRING(L"\\Device\\KernelGod");
UNICODE_STRING DeviceLink = RTL_CONSTANT_STRING(L"\\??\\KernelGod");

PDEVICE_OBJECT DeviceObj = NULL;